steps:

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=libosdev-dockerhub-secret > pass.txt' ]
    # this is a hack to get the BRANCH_NAME and SHORT_SHA in the build metadata even when
    # submitted from via ./gcloud/push.sh.  All --substitutions variables have to exist in the
    # yaml file.  Even when you are substiting special variables like BRANCH_NAME and SHORT_SHA (lame).
    env: 
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'

  - name: gcr.io/cloud-builders/docker
    entrypoint: "sh"
    args: ["-c", "docker login --username=libosdev --password-stdin < pass.txt"]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker pull docker.io/ucdlib/rp-ucd-fuseki:latest || true' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker build --cache-from docker.io/ucdlib/rp-ucd-fuseki:latest -t docker.io/ucdlib/rp-ucd-fuseki:$TAG_NAME .' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker tag docker.io/ucdlib/rp-ucd-fuseki:$TAG_NAME docker.io/ucdlib/rp-ucd-fuseki:latest' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker push docker.io/ucdlib/rp-ucd-fuseki:$TAG_NAME' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "sh"
    args: [ '-c', 'docker push docker.io/ucdlib/rp-ucd-fuseki:latest' ]