#! /usr/bin/env yml-docker-compose.sh
version: '3'
services:
  harvest:
    image: ucdlib/rp-ucd-harvest:dev
    command: tail -f /dev/null
    environment:
      - VIVO_BASEURI_PREFIX=http://experts.library.ucdavis.edu/
    env_file:
      - test.env
    volumes:
       - harvest-data:/usr/local/vivo/harvester/data
       - ./lib:/usr/local/lib/harvest
       - ./harvest:/usr/local/bin/harvest

volumes:
  harvest-data:
