#! /usr/bin/env yml-docker-compose.sh
version: '3'
services:
  harvest:
    image: ucdlib/rp-ucd-harvest:dev
    command: tail -f /dev/null
    environment:
      - VIVO_BASEURI_PREFIX=http://experts.library.ucdavis.edu/
    env_file:
      - .env
    volumes:
       - harvest-xslt-data:/usr/local/vivo/harvester/data
       - harvest-data:/var/lib/harvest
       - ./lib:/usr/local/lib/harvest
       - ./harvest:/usr/local/bin/harvest
       - ./cdl:/usr/local/bin/cdl
       - ./ucdid:/usr/local/bin/ucdid
       - ./elements/elements:/usr/local/bin/elements
       - ./aeq/aeq:/usr/local/bin/aeq

  fuseki:
    image: ucdlib/rp-ucd-fuseki:${FUSEKI_VERSION:-1.2.0}
    env_file:
      - .env
    volumes:
      - fuseki-data:/fuseki
    ports: # still exposed for admin access
      - ${FUSEKI_HOST_PORT:-3030}:3030


volumes:
  harvest-xslt-data:
  harvest-data:
  fuseki-data:
